import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { a } from "@react-spring/three";
import islandFab from "../assets/3d/tyisland.glb";

const Island = (props) => {
  const islandRef = useRef();
  const { nodes, materials } = useGLTF(islandFab);
  return (
    <a.group {...props} ref={islandRef} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cat_cat2_0.geometry}
        material={materials.cat2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Cube004_������������������"].geometry}
        material={materials.material_8}
      />
      <a.group rotation={[-Math.PI / 2, 0, 0]} scale={61.768}>
        <a.group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial120.geometry}
            material={materials.pozo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial123.geometry}
            material={materials.tierra}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial094.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial093.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial092.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial091.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial090.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial089.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial098.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial097.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial096.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial095.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial121.geometry}
            material={materials.pozo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial116.geometry}
            material={materials.maderas}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial114.geometry}
            material={materials.maderas}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial113.geometry}
            material={materials.maderas}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial115.geometry}
            material={materials.maderas}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial119.geometry}
            material={materials.pozo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial087.geometry}
            material={materials.nubes}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial086.geometry}
            material={materials.nubes}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial085.geometry}
            material={materials.nubes}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial084.geometry}
            material={materials.nubes}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial083.geometry}
            material={materials.nubes}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial082.geometry}
            material={materials.nubes}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial081.geometry}
            material={materials.nubes}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial079.geometry}
            material={materials.nubes}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial078.geometry}
            material={materials.nubes}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial112.geometry}
            material={materials.maderas}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial111.geometry}
            material={materials.maderas}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial110.geometry}
            material={materials.maderas}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial109.geometry}
            material={materials.maderas}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial069.geometry}
            material={materials.piedras2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial068.geometry}
            material={materials.piedras2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial067.geometry}
            material={materials.piedras2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial066.geometry}
            material={materials.piedras2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial065.geometry}
            material={materials.piedras2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial064.geometry}
            material={materials.piedras2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial063.geometry}
            material={materials.piedras2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial077.geometry}
            material={materials.piedras2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial076.geometry}
            material={materials.piedras2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial075.geometry}
            material={materials.piedras2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial074.geometry}
            material={materials.piedras2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial073.geometry}
            material={materials.piedras2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial072.geometry}
            material={materials.piedras2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial071.geometry}
            material={materials.piedras2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial070.geometry}
            material={materials.piedras2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial042.geometry}
            material={materials.puerta}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial056.geometry}
            material={materials.paredes}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial057.geometry}
            material={materials.botella_de_vidrio}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial046.geometry}
            material={materials.techo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial050.geometry}
            material={materials.puerta}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial040.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial039.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial054.geometry}
            material={materials.paredes}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial047.geometry}
            material={materials.adornos}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial058.geometry}
            material={materials.paredes}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial012.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial014.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial016.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial018.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial020.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial022.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial024.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial026.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial028.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial030.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial032.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial034.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial036.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial011.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial013.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial015.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial017.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial019.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial021.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial023.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial025.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial027.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial029.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial031.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial033.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial035.geometry}
            material={materials.arbol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial051.geometry}
            material={materials.puerta}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial062.geometry}
            material={materials.peces}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial043.geometry}
            material={materials.adornos}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial061.geometry}
            material={materials.peces}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial060.geometry}
            material={materials.peces}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial059.geometry}
            material={materials.peces}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial045.geometry}
            material={materials.botella_de_vidrio}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial053.geometry}
            material={materials.paredes}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial052.geometry}
            material={materials.puerta}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial041.geometry}
            material={materials.puerta}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial037.geometry}
            material={materials.adornos}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial044.geometry}
            material={materials.adornos}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial003.geometry}
            material={materials.piedras1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial004.geometry}
            material={materials.piedras1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial005.geometry}
            material={materials.piedras1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial006.geometry}
            material={materials.piedras1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial007.geometry}
            material={materials.piedras1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial008.geometry}
            material={materials.piedras1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial009.geometry}
            material={materials.piedras1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial010.geometry}
            material={materials.piedras1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial002.geometry}
            material={materials.piedras1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial001.geometry}
            material={materials.piedras1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial055.geometry}
            material={materials.techo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial048.geometry}
            material={materials.techo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial049.geometry}
            material={materials.adornos}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial038.geometry}
            material={materials.adornos}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial.geometry}
            material={materials.pozo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial108.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial107.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial106.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial105.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial104.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial103.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial102.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial101.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial100.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial099.geometry}
            material={materials.fogata}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial088.geometry}
            material={materials.piedras1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial118.geometry}
            material={materials.pozo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial122.geometry}
            material={materials.pozo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial117.geometry}
            material={materials.pozo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial124.geometry}
            material={materials.pasto}
          />
        </a.group>
      </a.group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.005"]}
      />
      <a.group
        position={[-30.913, 19.834, -9.314]}
        rotation={[-Math.PI / 2, 0, 1.343]}
        scale={0.444}
      >
        <a.group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial125.geometry}
            material={materials.roof}
            position={[6.735, -4.292, 3.922]}
            rotation={[0, -0.228, 0]}
            scale={0.649}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial126.geometry}
            material={materials.horizontal_post}
            position={[6.735, -4.292, 3.922]}
            rotation={[0, -0.228, 0]}
            scale={0.649}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial127.geometry}
            material={materials.vertical_posts}
            position={[6.735, -4.292, 3.922]}
            rotation={[0, -0.228, 0]}
            scale={0.649}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial128.geometry}
            material={materials.sign_background}
            position={[6.735, -4.292, 3.922]}
            rotation={[0, -0.228, 0]}
            scale={0.649}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial129.geometry}
            material={materials.top_posts}
            position={[6.735, -4.292, 3.922]}
            rotation={[0, -0.228, 0]}
            scale={0.649}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial130.geometry}
            material={materials.sidewyas_posts}
            position={[6.735, -4.292, 3.922]}
            rotation={[0, -0.228, 0]}
            scale={0.649}
          />
        </a.group>
      </a.group>
      <a.group
        position={[3.553, 19.328, 34.171]}
        rotation={[-Math.PI / 2, 0, 3.101]}
        scale={1.922}
      >
        <a.group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial131.geometry}
            material={materials.lambert1}
            position={[1.652, 0, -0.067]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial132.geometry}
            material={materials.lambert1}
            position={[1.652, 0, -0.067]}
          />
        </a.group>
      </a.group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={nodes.Text001.material}
        position={[1.705, 20.023, 33.871]}
        rotation={[1.611, 0.013, -3.082]}
        scale={0.784}
      />
    </a.group>
  );
};

export default Island;
