/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useContext, useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { a } from "@react-spring/three";
import tyFab from "../assets/3d/ty.glb";
import { PlayerControlContext } from "../store/PlayerControls";

const TyCharacter = (props) => {
  const groupRef = useRef();
  const { nodes, materials, animations } = useGLTF(tyFab);
  const { actions, names } = useAnimations(animations, groupRef);
  const { keyPressed } = useContext(PlayerControlContext);

  useEffect(() => {
    actions[names[keyPressed]]?.reset().fadeIn(0.5).play();
    return () => actions[names[keyPressed]]?.fadeOut(0.5);
  }, [keyPressed]);

  return (
    <a.group castShadow ref={groupRef} {...props} dispose={null}>
      <a.group castShadow name="Scene">
        <a.group castShadow name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <skinnedMesh
            receiveShadow
            castShadow
            name="Boy01_Hair_Geo"
            geometry={nodes.Boy01_Hair_Geo.geometry}
            material={materials["Boy01_Hair_MAT.004"]}
            skeleton={nodes.Boy01_Hair_Geo.skeleton}
          />
          <skinnedMesh
            receiveShadow
            castShadow
            name="Boy01_Hands_Geo"
            geometry={nodes.Boy01_Hands_Geo.geometry}
            material={materials["Boy01_Hands_MAT.004"]}
            skeleton={nodes.Boy01_Hands_Geo.skeleton}
          />
          <skinnedMesh
            name="Boy01_Head_Geo"
            geometry={nodes.Boy01_Head_Geo.geometry}
            material={materials["Boy01_Head_MAT.004"]}
            skeleton={nodes.Boy01_Head_Geo.skeleton}
          />
          <skinnedMesh
            receiveShadow
            castShadow
            name="Boy01_LowerBody_Geo"
            geometry={nodes.Boy01_LowerBody_Geo.geometry}
            material={materials["Boy01_LowerBody_MAT.004"]}
            skeleton={nodes.Boy01_LowerBody_Geo.skeleton}
          />
          <skinnedMesh
            receiveShadow
            castShadow
            name="Boy01_Scarf_Geo"
            geometry={nodes.Boy01_Scarf_Geo.geometry}
            material={materials["Boy01_Scarf_MAT.004"]}
            skeleton={nodes.Boy01_Scarf_Geo.skeleton}
          />
          <skinnedMesh
            receiveShadow
            castShadow
            name="Boy01_Shoes_Geo"
            geometry={nodes.Boy01_Shoes_Geo.geometry}
            material={materials["Boy01_Shoes_MAT.004"]}
            skeleton={nodes.Boy01_Shoes_Geo.skeleton}
          />
          <skinnedMesh
            receiveShadow
            castShadow
            name="Boy01_UpperBody_Geo"
            geometry={nodes.Boy01_UpperBody_Geo.geometry}
            material={materials["Boy01_UpperBody_MAT.004"]}
            skeleton={nodes.Boy01_UpperBody_Geo.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </a.group>
      </a.group>
    </a.group>
  );
};

useGLTF.preload("/ty.glb");

export default TyCharacter;
